### ISSUE TITLE
BaseTower does not resume firing if there is not a target within a few seconds of game start

### ISSUE THREAD

**Issue by octoshrimpy** [octoshrimpy/bugbots#1]

**Comment by Rockster160** [comment]
Fixed via [594125b](https://github.com/octoshrimpy/bugbots/commit/594125b47f5aa7be1aee54711fa6f4af7a7cc4a4)

**Comment by Rockster160** [comment]
Turns out this was actually a rotation issue- Once the gun does a full rotation, it doesn't align with the `goto_rotation`
Solved by modding `%` the `rotation_difference`
